include:
  - board: nice_nano
    shield: settings_reset
  - board: nice_nano
    shield: cosmos_left
    snippet: zmk-usb-logging
  - board: nice_nano
    shield: cosmos_right
    snippet: zmk-usb-logging
